Execution command that leads to crash (executed from src directory)- 
    "./targets/gdb/gdb/gdb < observed-failures/gdb/v8.1/l10" (returns 139 or -11)

these inputs were generated by the command-
    "python3 generate_argfiles.py -p --seed 30083 --length-level 2"
