Execution command that leads to crash (executed from src directory)- 
    "./latest-targets/gdb/gdb/gdb < observed-failures/gdb/v11.1/l10" (returns 134 or -6, which is different return code than v8.1)

these inputs were generated by the command-
    "python3 generate_argfiles.py -p --seed 30083 --length-level 2"
